/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_ui_ReversiBoard_GameReversi
  (JNIEnv *, jobject , jint , jint , jint);

JNIEXPORT jint JNICALL Java_ui_ReversiBoard_StateReversi
  (JNIEnv *, jobject , jint);

#ifdef __cplusplus
}
#endif
#endif