/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_ui_SnakeAndLaddersBoard_GameSnakesAndLadders
  (JNIEnv *, jobject , jint ,jint ,jint);

JNIEXPORT jint JNICALL Java_ui_SnakeAndLaddersBoard_DiceSnakesAndLadders
  (JNIEnv *, jobject );

#ifdef __cplusplus
}
#endif
#endif