/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ui_ReversiBoard */

#ifndef _Included_ui_ReversiBoard
#define _Included_ui_ReversiBoard
#ifdef __cplusplus
extern "C" {
#endif
#undef ui_ReversiBoard_BASELINE_OFFSET_SAME_AS_HEIGHT
#define ui_ReversiBoard_BASELINE_OFFSET_SAME_AS_HEIGHT -InfD
#undef ui_ReversiBoard_EPSILON_ABSOLUTE
#define ui_ReversiBoard_EPSILON_ABSOLUTE 1.0E-5
#undef ui_ReversiBoard_DEFAULT_TRANSLATE_X
#define ui_ReversiBoard_DEFAULT_TRANSLATE_X 0.0
#undef ui_ReversiBoard_DEFAULT_TRANSLATE_Y
#define ui_ReversiBoard_DEFAULT_TRANSLATE_Y 0.0
#undef ui_ReversiBoard_DEFAULT_TRANSLATE_Z
#define ui_ReversiBoard_DEFAULT_TRANSLATE_Z 0.0
#undef ui_ReversiBoard_DEFAULT_SCALE_X
#define ui_ReversiBoard_DEFAULT_SCALE_X 1.0
#undef ui_ReversiBoard_DEFAULT_SCALE_Y
#define ui_ReversiBoard_DEFAULT_SCALE_Y 1.0
#undef ui_ReversiBoard_DEFAULT_SCALE_Z
#define ui_ReversiBoard_DEFAULT_SCALE_Z 1.0
#undef ui_ReversiBoard_DEFAULT_ROTATE
#define ui_ReversiBoard_DEFAULT_ROTATE 0.0
#undef ui_ReversiBoard_EFFECTIVE_ORIENTATION_LTR
#define ui_ReversiBoard_EFFECTIVE_ORIENTATION_LTR 0L
#undef ui_ReversiBoard_EFFECTIVE_ORIENTATION_RTL
#define ui_ReversiBoard_EFFECTIVE_ORIENTATION_RTL 1L
#undef ui_ReversiBoard_EFFECTIVE_ORIENTATION_MASK
#define ui_ReversiBoard_EFFECTIVE_ORIENTATION_MASK 1L
#undef ui_ReversiBoard_AUTOMATIC_ORIENTATION_LTR
#define ui_ReversiBoard_AUTOMATIC_ORIENTATION_LTR 0L
#undef ui_ReversiBoard_AUTOMATIC_ORIENTATION_RTL
#define ui_ReversiBoard_AUTOMATIC_ORIENTATION_RTL 2L
#undef ui_ReversiBoard_AUTOMATIC_ORIENTATION_MASK
#define ui_ReversiBoard_AUTOMATIC_ORIENTATION_MASK 2L
#undef ui_ReversiBoard_DEFAULT_CACHE
#define ui_ReversiBoard_DEFAULT_CACHE 0L
#undef ui_ReversiBoard_DEFAULT_DISABLE
#define ui_ReversiBoard_DEFAULT_DISABLE 0L
#undef ui_ReversiBoard_DEFAULT_MOUSE_TRANSPARENT
#define ui_ReversiBoard_DEFAULT_MOUSE_TRANSPARENT 0L
#undef ui_ReversiBoard_DIRTY_CHILDREN_THRESHOLD
#define ui_ReversiBoard_DIRTY_CHILDREN_THRESHOLD 10L
#undef ui_ReversiBoard_REMOVED_CHILDREN_THRESHOLD
#define ui_ReversiBoard_REMOVED_CHILDREN_THRESHOLD 20L
#undef ui_ReversiBoard_USE_PREF_SIZE
#define ui_ReversiBoard_USE_PREF_SIZE -InfD
#undef ui_ReversiBoard_USE_COMPUTED_SIZE
#define ui_ReversiBoard_USE_COMPUTED_SIZE -1.0
#undef ui_ReversiBoard_REMAINING
#define ui_ReversiBoard_REMAINING 2147483647L
#undef ui_ReversiBoard_GRID_LINE_DASH
#define ui_ReversiBoard_GRID_LINE_DASH 3.0
/*
 * Class:     ui_ReversiBoard
 * Method:    GameReversi
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_ui_ReversiBoard_GameReversi
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
